version: '3.3'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - scheduler
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - DATABASE_URL=sqlite:///./sql_app.db

  scheduler:
    build: .
    command: python -m app.scheduler
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DISABLE_TEXTSEARCH=1

volumes:
  mongodb_data: